groups:
  - name: host-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Uso alto de CPU"
          description: "CPU superior al 10%"
